theme: minima
title: Final Title
author: Ud
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Wlocome to Udbhav's blogs. Here is where I reflect upon and write down
  some important thoughts that come to my mind. Hope you like this!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
